### ISSUE TITLE
Value undefined out of range for undefined options property undefined

### ISSUE THREAD

**Issue by erfanhemmati** [graphology/graphology#433]
Hey guys.
I have 1,000,002 nodes and 16,777,216 edges.
I have to try add a new edge but i have an error like this:
```
RangeError: Value undefined out of range for undefined options property undefined
```
Thanks for your help.

**Comment by erfanhemmati** [comment]
My resource:
30 G Ram
16 Core CPU
i have to configured --max-old-space-size flag to 30,720

**Comment by Yomguithereal** [comment]
Do you have a stack trace or some code available somewhere? I cannot really pinpoint a potential issue here without this kind of info.

**Comment by erfanhemmati** [comment]
@Yomguithereal 
```
RangeError: Value undefined out of range for undefined options property undefined
    at Map.set (<anonymous>)
    at addEdge (/root/projects/apps/csv-parser/node_modules/graphology/dist/graphology.cjs.js:2860:16)
    at Graph.<computed> [as addEdge] (/root/projects/apps/csv-parser/node_modules/graphology/dist/graphology.cjs.js:4840:16)
    at /root/projects/apps/csv-parser/app.js:32:15
    at Array.forEach (<anonymous>)
    at /root/projects/apps/csv-parser/app.js:31:13
    at Layer.handle [as handle_request] (/root/projects/apps/csv-parser/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/projects/apps/csv-parser/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/root/projects/apps/csv-parser/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/root/projects/apps/csv-parser/node_modules/express/lib/router/layer.js:95:5)

```

this is stack trace

**Comment by erfanhemmati** [comment]
manually i want to to implement and find shortest bath between nodes in large scale. using Dijkstra algorithm
@Yomguithereal

**Comment by Yomguithereal** [comment]
It's difficult to say but basically it seems to me that using `--max-old-space-size` lower the maximum size of representable integers, which naturally mean you cannot index memory slots larger than this size, hence the RangeError. There is nothing I can do about this. Can you tell me whether you still have the issue without the flag?

Another hypothesis is that you are working on a 32bits system? Or that you restricted the range of ints of the engine to 32bits?

**Comment by erfanhemmati** [comment]
I'am using Ubuntu 22.04.1 LTS 64 bit.
Without using ``` --max-old-space-size``` flag i have v8 engine memory heap error.
Also i determined ``` --max-old-space-size``` flag to maximum in based on my server's memory

**Comment by erfanhemmati** [comment]
@Yomguithereal 
Does Graphology using the ```Set()``` to storing graph and their edges?

**Comment by erfanhemmati** [comment]
Also does this issue is related to my error?
https://github.com/nodejs/node/issues/37320

**Comment by Yomguithereal** [comment]
> Does Graphology using the Set() to storing graph and their edges?

It uses a lot of tailored data structure that range from linked lists, arrays, and ES6 Maps yes. But no Set per se. But it makes no difference in your case because the issue seem to be tied to the max int representable. If you need to store more items than that int, there is no way to index contiguous memory outside of that bound.

Note that usually heap errors tend to happen when you try to represent too large a string in javascript. So it could happen if you try to parse a text file without streaming. `graphology` should not be subject to that.

> Also does this issue is related to my error?

It could, yes. It's possible that on some architectures and OSes, v8 has a Set/Map implementation that cannot store more than a certain number of items. In which case you are out of luck as there is no way to guarantee optimal time complexity for a graph data structure without Set or Map (plain objects have other kind of issues).

This said, if you replace the global Map reference by a monkey patched implementation as found in the first reply to the nodejs issue your are linking. Or, based on your use case, it might be a good idea to implement a subset of the graphology spec that is required by the dijkstra function to work.

**Comment by Yomguithereal** [comment]
At one point I might add some kind of trick into the lib to make sure we can have more than 2^24 items in either nodes or edges but this won't happen shortly. The shortest way really is to try and override default Map with @Inrixia trick shown here: https://github.com/nodejs/node/issues/37320 Out of curiosity what kind of shortest path are you trying to extract here? single source to each other? a single path?

**Comment by erfanhemmati** [comment]
@Yomguithereal 
Thanks for your response.
I want find shortest path/s between two nodes. Node source and Node target. It might be have one path or multiple path but in my case find one path is enough for me.

**Comment by erfanhemmati** [comment]
@Yomguithereal 
Can we store and separate graph in multiple Set/Map?
This package is awesome for my use case and scenario if we resolve this issue and store more than 2^24 items in either nodes or edges.

**Comment by Yomguithereal** [comment]
> I want find shortest path/s between two nodes. Node source and Node target. It might be have one path or multiple path but in my case find one path is enough for me.

It should be yes, because in such large graph finding all the equivalent paths might be computationnally unfeasible due to combinatorial issues yes :)

**Comment by Yomguithereal** [comment]
> Can we store and separate graph in multiple Set/Map?

Yes, basically the idea would be to detect when you are adding a node or edge over the 2^24th one and swap the underlying Map with some maps container to avoid this. The issue though is that it makes lookups twice slower at that point which could be a performance issue in some cases also.

Another thing to explore here is implementing a subset of graphology specs suited to your use case, i.e. computing shortest path between source and target. But this is only a viable option if you don't need anything else than computing shortest path.

**Comment by Inrixia** [comment]
> The issue though is that it makes lookups twice slower at that point which could be a performance issue in some cases also.

Jumping in here adding this as a configurable option rather than attempting to detect would remove that overhead.

**Comment by Yomguithereal** [comment]
For instance, the bidirectional version of the Dijkstra algorithm, as implemented in `graphology` only requires `hasNode`, `inboundEdges`, `outboundEdges`, `opposite` and `getEdgeAttributes` so if you implement your own minimalist `graphology` object (adding the methods you need to create the graph), the shortest path function will work for you seemlessly.

**Comment by erfanhemmati** [comment]
@Yomguithereal
All I need is finding and computing shortest path between nodes in shortest time possible (high scale)

**Comment by Yomguithereal** [comment]
@Inrixia the overhead could be as small as checking the size of the current Map is less than 2^24. Which means until that point, the lookup overhead is none since the initial ES6 Map was not swapped by your solution yet. But this size `if` condition might cost too much indeed since the path should be as fast as possible, I need to benchmark.

**Comment by erfanhemmati** [comment]
> For instance, the bidirectional version of the Dijkstra algorithm, as implemented in `graphology` only requires `hasNode`, `inboundEdges`, `outboundEdges`, `opposite` and `getEdgeAttributes` so if you implement your own minimalist `graphology` object (adding the methods you need to create the graph), the shortest path function will work for you seemlessly.

how can i do this? is there any example?

**Comment by Inrixia** [comment]
> @Inrixia the overhead could be...
Exactly, Imo this issue will affect so few people that requiring a optional flag would be best as any additional if statements are a bad idea for performance code. Ofc implementing the optional flag you would want to not check the flag but use the flag to set which Set class you use on initialization removing the checks overhead from any thing after.

**Comment by Yomguithereal** [comment]
> All I need is finding and computing shortest path between nodes in shortest time possible (high scale)

In which case it would also not be absurd to reimplement using low-level structures such as byte arrays and such this logic here: https://github.com/graphology/graphology/blob/master/src/shortest-path/dijkstra.js#L57-L164 to work with your data. But I don't know the time you have etc. and what kind of scale you want to reach etc. (maybe node.js is not a good fit and using C or rust is a better idea also). Most of the heavy work in the function is actually done by [`mnemonist`](https://yomguithereal.github.io/mnemonist/) heaps.

**Comment by Yomguithereal** [comment]
@Inrixia you are right. I just don't want to do it as an instance option because those are specified and reimplemented in many custom implementations this and there (because there is no silver-bullet way to implement a graph, I just maintain the one optimized for the most use-case but I sacrifice memory for better time complexities overall) and this could break them. I think I will go this way:

```js
const graph = new Graph();
graph.ENABLE_SUPER_STUFF_MEMORY_LARGE_BIGGY_WHATEVER = true
```

**Comment by Inrixia** [comment]
Sounds good, and yea I'm surprised no further progress has been made on the original issue.

**Comment by aldipermanaetikaputra** [comment]
Hello everyone, 

I wanted to let you know that I just published a new package `large-set`: https://github.com/aldipermanaetikaputra/large-set. It can handle a much larger number of elements than the default limit of $2^{24}$ or $16.777.216$, without sacrificing performance. Feel free to give it a try!

**Comment by Inrixia** [comment]
> It can handle a much larger number of elements than the default limit of 224 or 16.777.216, without sacrificing performance. Feel free to give it a try!

Nice library, it uses the same method I was to get around the limitation, but please don't claim it does not have a performance impact that's incorrect. Base performance will be worse than a default set and as a set grows performance will degrade, same as with my original solution.

**Comment by aldipermanaetikaputra** [comment]
> > It can handle a much larger number of elements than the default limit of 224 or 16.777.216, without sacrificing performance. Feel free to give it a try!
> 
> Nice library, it uses the same method I was to get around the limitation, but please don't claim it does not have a performance impact that's incorrect. Base performance will be worse than a default set and as a set grows performance will degrade, same as with my original solution.

You are correct that the partitioning of the set into smaller sets can incur a performance penalty. What I meant before is that the library can handle a much larger number of elements than the default limit without sacrificing performance as much as possible. Thanks for your feedback!
