### ISSUE TITLE
rollup building: Property 'getNodeAttribute' does not exist on type 'DirectedGraph<IGraphNodeAttributes, IGraphEdgeAttributes, Attributes>'

### ISSUE THREAD

**Issue by linonetwo** [graphology/graphology#467]
```ts
import { DirectedGraph } from 'graphology';
import { weightedInDegree, weightedOutDegree } from 'graphology-metrics/node/weighted-degree';
```

Code is very simple, and in VSCode it is all fine.

But when build with rollup:

```
> rollup --config rollup.config.ts --configPlugin swc3


src/index.ts → dist...
src/services/graphContainer/graph.ts(50,44): error TS2339: Property 'getNodeAttribute' does not exist on type 'DirectedGraph<IGraphNodeAttributes, IGraphEdgeAttributes, Attributes>'.
src/services/graphContainer/graph.ts(72,44): error TS2339: Property 'findNode' does not exist on type 'DirectedGraph<IGraphNodeAttributes, IGraphEdgeAttributes, Attributes>'.
src/services/graphContainer/graph.ts(72,53): error TS7006: Parameter 'node' implicitly has an 'any' type.
src/services/graphContainer/graph.ts(75,35): error TS2339: Property 'getNodeAttribute' does not exist on type 'DirectedGraph<IGraphNodeAttributes, IGraphEdgeAttributes, Attributes>'.
src/services/graphContainer/graph.ts(87,23): error TS2339: Property 'inNeighbors' does not exist on type 'DirectedGraph<IGraphNodeAttributes, IGraphEdgeAttributes, Attributes>'.
src/services/graphContainer/graph.ts(87,47): error TS7006: Parameter 'nodeID' implicitly has an 'any' type.
src/services/graphContainer/graph.ts(87,68): error TS2339: Property 'getNodeAttribute' does not exist on type 'DirectedGraph<IGraphNodeAttributes, IGraphEdgeAttributes, Attributes>'.
src/services/graphContainer/graph.ts(87,109): error TS7006: Parameter 'node' implicitly has an 'any' type.
src/services/graphContainer/graph.ts(94,29): error TS2339: Property 'getNodeAttribute' does not exist on type 'DirectedGraph<IGraphNodeAttributes, IGraphEdgeAttributes, Attributes>'.
src/services/graphContainer/graph.ts(106,29): error TS2339: Property 'getNodeAttribute' does not exist on type 'DirectedGraph<IGraphNodeAttributes, IGraphEdgeAttributes, Attributes>'.
src/services/graphContainer/graph.ts(121,18): error TS2339: Property 'addNode' does not exist on type 'DirectedGraph<IGraphNodeAttributes, IGraphEdgeAttributes, Attributes>'.
src/services/graphContainer/graph.ts(133,31): error TS2339: Property 'getNodeAttribute' does not exist on type 'DirectedGraph<IGraphNodeAttributes, IGraphEdgeAttributes, Attributes>'.
src/services/graphContainer/graph.ts(134,29): error TS2339: Property 'getNodeAttribute' does not exist on type 'DirectedGraph<IGraphNodeAttributes, IGraphEdgeAttributes, Attributes>'.
src/services/graphContainer/graph.ts(154,18): error TS2339: Property 'addEdge' does not exist on type 'DirectedGraph<IGraphNodeAttributes, IGraphEdgeAttributes, Attributes>'.
src/services/graphContainer/graph.ts(159,23): error TS2339: Property 'outNeighbors' does not exist on type 'DirectedGraph<IGraphNodeAttributes, IGraphEdgeAttributes, Attributes>'.
src/services/graphContainer/graph.ts(168,18): error TS2339: Property 'forEachNode' does not exist on type 'DirectedGraph<IGraphNodeAttributes, IGraphEdgeAttributes, Attributes>'.
src/services/graphContainer/graph.ts(169,24): error TS2339: Property 'getNodeAttribute' does not exist on type 'DirectedGraph<IGraphNodeAttributes, IGraphEdgeAttributes, Attributes>'.
src/services/graphContainer/graph.ts(179,20): error TS2339: Property 'getNodeAttribute' does not exist on type 'DirectedGraph<IGraphNodeAttributes, IGraphEdgeAttributes, Attributes>'.
src/services/graphContainer/graph.ts(186,16): error TS2339: Property 'neighbors' does not exist on type 'DirectedGraph<IGraphNodeAttributes, IGraphEdgeAttributes, Attributes>'.

[!] (plugin dts) RollupError: Failed to compile. Check the logs above.
src/services/graphContainer/graph.ts
    at error (/Users/linonetwo/Desktop/repo/memeloop/node_modules/.pnpm/rollup@3.20.2/node_modules/rollup/dist/shared/rollup.js:274:30)
    at Object.error (/Users/linonetwo/Desktop/repo/memeloop/node_modules/.pnpm/rollup@3.20.2/node_modules/rollup/dist/shared/rollup.js:24694:20)
    at Object.error (/Users/linonetwo/Desktop/repo/memeloop/node_modules/.pnpm/rollup@3.20.2/node_modules/rollup/dist/shared/rollup.js:23888:42)
    at generateDtsFromTs (file:///Users/linonetwo/Desktop/repo/memeloop/node_modules/.pnpm/rollup-plugin-dts@5.3.0_rollup@3.20.2_typescript@5.0.4/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1697:30)
    at Object.transform (file:///Users/linonetwo/Desktop/repo/memeloop/node_modules/.pnpm/rollup-plugin-dts@5.3.0_rollup@3.20.2_typescript@5.0.4/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1706:38)
    at /Users/linonetwo/Desktop/repo/memeloop/node_modules/.pnpm/rollup@3.20.2/node_modules/rollup/dist/shared/rollup.js:24893:40
```

**Comment by linonetwo** [comment]
Fixed by `pnpm add -D graphology-types`

Which is very weird. This should be auto pickup.

**Comment by linonetwo** [comment]
```
    "graphology": "^0.25.1",
    "graphology-metrics": "^2.1.0",

  "devDependencies": {
    "graphology-types": "^0.24.7"
  }
```

and

```
    "rollup": "^3.20.2",
    "rollup-plugin-dts": "^5.3.0",
    "rollup-plugin-swc3": "^0.8.1",
    "rollup-plugin-ts": "^3.2.0",
```

no beta version.

As long as this workaround works, close in advance.
